Base Functionality all working - see README

diff --git a/templates/db_dump.sh.erb b/templates/db_dump.sh.erb
--- a/templates/db_dump.sh.erb
+++ b/templates/db_dump.sh.erb
@@ -1,13 +1,21 @@
 #!/bin/bash
 # This file is managed by Puppet
+SCRIPTNAME=$(basename $0)
 
-/bin/logger "Starting dump of database: <%= @db_name %>"
+logger "PE_FAILOVER: ${SCRIPTNAME} ---> Starting dump of database: <%= @db_name %>"
 
-<%= @pg_dump_command %> <%= @db_name %> -f <%= @dump_path %>/<%= @db_name %>/<%= @db_name %>_<%= @timestamp_command %>.bin
-
+# Create Export
+su - pe-postgres -s '/bin/bash' -c "<%= @pg_dump_command %> -C <%= @db_name %> -f <%= @dump_path %>/<%= @db_name %>/<%= @db_name %>_latest.psql"
 result="$?"
 if [[ $result -eq 0 ]]; then
-  /bin/logger "Completed dump of database: <%= @db_name %>"
+  logger "PE_FAILOVER: ${SCRIPTNAME} ---> Completed dump of database: <%= @db_name %>"
 else
-  /bin/logger "Failed to dump database <%= @db_name %>. Exit code is: ${result}"
+  logger "PE_FAILOVER: ${SCRIPTNAME} ---> Failed to dump database <%= @db_name %>. Exit code is: ${result}"
+fi
+
+# Create MD5SUM file for Export
+<%= @md5sum_command %> <%= @dump_path %>/<%= @db_name %>/<%= @db_name %>_latest.psql > <%= @dump_path %>/<%= @db_name %>/<%= @db_name %>_latest.psql.md5sum
+
+if [ $? -ne 0 ]; then
+  logger "PE_FAILOVER: ${SCRIPTNAME} ---> Failed to create MD5Sum for export!"
 fi
diff --git a/templates/nc_dump.sh.erb b/templates/nc_dump.sh.erb
--- a/templates/nc_dump.sh.erb
+++ b/templates/nc_dump.sh.erb
@@ -1,6 +1,7 @@
 #!/bin/bash
 PRIMARY_MASTER=<%= @fqdn %>
 SECONDARY_MASTER=<%= @passive_master %>
+SCRIPTNAME=$(basename $0)
 
 PATH="/opt/puppetlabs/bin:/opt/puppetlabs/puppet/bin:/opt/puppet/bin:$PATH"
 declare -x PE_CERT=$(puppet agent --configprint hostcert)
@@ -8,4 +9,11 @@ declare -x PE_KEY=$(puppet agent --configprint hostprivkey)
 declare -x PE_CA=$(puppet agent --configprint localcacert)
 declare -x NC_CURL_OPT="-s --cacert $PE_CA --cert $PE_CERT --key $PE_KEY --insecure"
 
-curl $NC_CURL_OPT --insecure https://$PRIMARY_MASTER:4433/classifier-api/v1/groups|sed "s/$PRIMARY_MASTER/$SECONDARY_MASTER/g" > <%= @nc_dump_path %>/nc_dump.<%= @timestamp_command %>.json
+logger "PE_FAILOVER: ${SCRIPTNAME} ---> Starting NC Export"
+curl $NC_CURL_OPT --insecure https://$PRIMARY_MASTER:4433/classifier-api/v1/groups|sed "s/$PRIMARY_MASTER/$SECONDARY_MASTER/g" > <%= @nc_dump_path %>/nc_dump.latest.json
+if [ $? -ne 0 ]; then
+  logger "PE_FAILOVER: ${SCRIPTNAME} ---> ERROR! Failed to export NC data, error code: $?"
+else
+  logger "PE_FAILOVER: ${SCRIPTNAME} ---> Export Completed."
+fi
+
diff --git a/templates/nc_rest.sh.erb b/templates/nc_rest.sh.erb
--- a/templates/nc_rest.sh.erb
+++ b/templates/nc_rest.sh.erb
@@ -1,12 +1,36 @@
 #!/bin/bash
 SECONDARY_MASTER=<%= @fqdn %>
-BKUP_FILE=`ls -lr <%= @nc_dump_path %>/*.json|tail -1`
+BKUP_FILE="<%= @nc_dump_path %>/nc_dump.latest.json"
+SCRIPTNAME=$(basename $0)
 
-PATH="/opt/puppetlabs/bin:/opt/puppetlabs/puppet/bin:/opt/puppet/bin:$PATH"
-declare -x PE_CERT=$(puppet agent --configprint hostcert)
-declare -x PE_KEY=$(puppet agent --configprint hostprivkey)
-declare -x PE_CA=$(puppet agent --configprint localcacert)
-declare -x NC_CURL_OPT="-s --cacert $PE_CA --cert $PE_CERT --key $PE_KEY --insecure -X POST"
+logger "PE_FAILOVER: ${SCRIPTNAME} ---> Started."
 
-curl $NC_CURL_OPT --insecure -T $BKUP_FILE https://$SECONDARY_MASTER:4433/classifier-api/v1/import-hierarchy
+if [ -f $BKUP_FILE ]; then
+  PATH="/opt/puppetlabs/bin:/opt/puppetlabs/puppet/bin:/opt/puppet/bin:$PATH"
+  declare -x PE_CERT=$(puppet agent --configprint hostcert)
+  declare -x PE_KEY=$(puppet agent --configprint hostprivkey)
+  declare -x PE_CA=$(puppet agent --configprint localcacert)
+  declare -x NC_CURL_OPT="-s --cacert $PE_CA --cert $PE_CERT --key $PE_KEY --insecure -X POST"
+
+  OUTPUT=$(curl $NC_CURL_OPT --insecure -T $BKUP_FILE https://$SECONDARY_MASTER:4433/classifier-api/v1/import-hierarchy)
+  if [ $? -eq 0 ]; then
+    mv $BKUP_FILE <%= @nc_dump_path %>/archive/nc_dump.<%= @timestamp_command %>.json
+    if [ $? -ne 0 ]; then
+      logger "PE_FAILOVER: ${SCRIPTNAME} ---> Failed to archive backup file [${BKUP_FILE}]!"
+      exit 1
+    fi
+  else
+    logger "PE_FAILOVER: ${SCRIPTNAME} ---> Failed to import backup file [${BKUP_FILE}]!"
+    logger "PE_FAILOVER: ${SCRIPTNAME} ---> Error: ${OUTPUT}"
+    exit 2
+  fi
+else
+  logger "PE_FAILOVER: ${SCRIPTNAME} ---> No backup file found, skipping import"
+  exit 0
+fi
+
+logger "PE_FAILOVER: ${SCRIPTNAME} ---> Completed."
+
+
+
 
diff --git a/templates/rest_dbs.sh.erb b/templates/rest_dbs.sh.erb
--- a/templates/rest_dbs.sh.erb
+++ b/templates/rest_dbs.sh.erb
@@ -1,51 +1,119 @@
 #!/bin/bash
 # Managed by Puppet
 # Restore Database exports created on master
+SCRIPTNAME=$(basename $0)
 
 manage_service() {
-  logger "Attempting to ${1} service ${2}..."
-  systemctl $1 $2 
+  logger "PE_FAILOVER: ${SCRIPTNAME} ---> Attempting to ${1} service ${2}..."
+
+  [ $1 == 'stop' ]  && ACTION='stopped'
+  [ $1 == 'start' ] && ACTION='running'
+
+  OUTPUT=$(/opt/puppetlabs/bin/puppet resource service $2 ensure=$ACTION)
   if [ $? -ne 0 ]; then
-    echo "Error! Failed to ${1} service ${2}; exiting!"
+    logger "PE_FAILOVER: ${SCRIPTNAME} ---> Error! Failed to ${1} service ${2}; exiting!"
     exit 1
   fi
-  logger "Completed ${1} on service ${2}"
+  logger "PE_FAILOVER: ${SCRIPTNAME} ---> Completed ${1} on service ${2}"
 }
 
 
 # Main
+logger "PE_FAILOVER: ${SCRIPTNAME} ---> Started."
+
+# Create Lockfile
+if [ ! -f "/var/tmp/${SCRIPTNAME}.lock" ]; then
+  touch "/var/tmp/${SCRIPTNAME}.lock"
+else
+  logger "PE_FAILOVER: ${SCRIPTNAME} ---> Script Already running! Exiting..."
+  exit 0
+fi
+
+# Set dump location for DB exports to restore
 DUMP_LOCATION="<%= @dump_path %>"
 
-#Stop Services
-manage_service 'stop' pe-orchestration-services.service
-manage_service 'stop' pe-nginx.service
-manage_service 'stop' pe-console-services.service
-manage_service 'stop' pe-puppetserver.service
+# Determine if there is data to restore PRIOR to killing services
+CHECK=$(find $DUMP_LOCATION -path 'archive' -prune -o -type f -name *_latest.psql)
 
-for db in $(find $DUMP_LOCATION/* -maxdepth 1 -type d)
-do
-  REST_FILE=$(ls -tr $db/*.bin|tail -1)
-  if [ -f $REST_FILE ]; then
+if [ ! -z "${CHECK}" ]; then
+
+  #Stop Services
+  manage_service 'stop' puppet
+  manage_service 'stop' pe-orchestration-services
+  manage_service 'stop' pe-nginx
+  manage_service 'stop' pe-console-services
+  manage_service 'stop' pe-puppetserver
+  manage_service 'stop' pe-puppetdb
+
+  for db in $(find $DUMP_LOCATION/* -maxdepth 1 -type d)
+  do
     DB_NAME=$(basename $db)
-    logger "Dropping database ${DB_NAME}"
-    sudo -u pe-postgres -s /bin/bash -c "/opt/puppetlabs/server/bin/dropdb ${DB_NAME}"
-    if [ $? -ne 0 ]; then
-      logger "Failed to drop database ${DB_NAME}, exiting with services DOWN!!!"
-      exit 2
-    fi
+    REST_FILE="${db}/${DB_NAME}_latest.psql"
+    if [ -f $REST_FILE ]; then
+      MD5RESULT=$(<%= @md5sum_command %> -c  $REST_FILE.md5sum)
+      if [ $? -eq 0  ]; then
+        logger "PE_FAILOVER: ${SCRIPTNAME} ---> Dropping database ${DB_NAME}"
+        su - pe-postgres -s /bin/bash -c "/opt/puppetlabs/server/bin/dropdb ${DB_NAME}"
+        if [ $? -ne 0 ]; then
+          logger "PE_FAILOVER: ${SCRIPTNAME} ---> Failed to drop database ${DB_NAME}, exiting with services DOWN!!!"
+          exit 2
+        fi
 
-    logger "Restoring database ${DB_NAME}"
-    su - pe-postgres -s /bin/bash -c "/opt/puppetlabs/server/bin/psql < $REST_FILE"
-    if [ $? -ne 0 ]; then
-      logger "Failed to restore database ${DB_NAME}, exiting with services DOWN!!!"
-      exit 3
+        logger "PE_FAILOVER: ${SCRIPTNAME} ---> Restoring database ${DB_NAME}"
+        su - pe-postgres -s /bin/bash -c "/opt/puppetlabs/server/bin/psql -v ON_ERROR_STOP=1 < $REST_FILE &>/dev/null"
+        if [ $? -ne 0 ]; then
+          logger "PE_FAILOVER: ${SCRIPTNAME} ---> Failed to restore database ${DB_NAME}, exiting with services DOWN!!!"
+          exit 3
+        fi
+
+        # Move dump file to archive
+        if [ ! -d "${db}/archive" ]; then
+          mkdir "${db}/archive"
+          if [ $? -ne 0 ]; then
+            logger "PE_FAILOVER: ${SCRIPTNAME} ---> Failed to create ${DB_NAME} archive location! Trying to continue..."
+          fi
+        fi
+
+        mv $REST_FILE "${db}/archive/${DB_NAME}_<%= @timestamp_command %>.psql"
+        if [ $? -ne 0 ]; then
+          logger "PE_FAILOVER: ${SCRIPTNAME} ---> Failed to move database export ${REST_FILE} to archive location! Trying to continue..."
+        fi
+
+        mv $REST_FILE.md5sum "${db}/archive/${DB_NAME}_<%= @timestamp_command %>.psql.md5sum"
+        if [ $? -ne 0 ]; then
+          logger "PE_FAILOVER: ${SCRIPTNAME} ---> Failed to move md5sum file ${REST_FILE}.md5sum to archive location! Trying to continue..."
+        fi
+
+        logger "PE_FAILOVER: ${SCRIPTNAME} ---> Succesfully restored database ${DB_NAME}"
+      else
+        logger "PE_FAILOVER: ${SCRIPTNAME} ---> Failed to verify md5sum for ${DB_NAME} archive! Skipping this database and continuing..."
+      fi
     fi
-    logger "Succesfully restored database ${DB_NAME}"
+  done
+
+  #Start Services
+  manage_service 'start' pe-puppetdb
+  manage_service 'start' pe-orchestration-services
+  manage_service 'start' pe-nginx
+  manage_service 'start' pe-console-services
+  manage_service 'start' pe-puppetserver
+  manage_service 'start' puppet
+
+  # Cleanup lockfile
+  rm -f "/var/tmp/${SCRIPTNAME}.lock"
+  if [ $? -ne 0 ]; then
+    logger "PE_FAILOVER: ${SCRIPTNAME} ---> Failed to remove lockfile! Exiting..."
+    exit 4
   fi
-done
 
-#Start Services
-manage_service 'start' pe-orchestration-services.service
-manage_service 'start' pe-nginx.service
-manage_service 'start' pe-console-services.service
-manage_service 'start' pe-puppetserver.service
+  logger "PE_FAILOVER: ${SCRIPTNAME} ---> Completed."
+else
+  logger "PE_FAILOVER: ${SCRIPTNAME} ---> No database exports found to restore!"
+  # Cleanup lockfile
+  rm -f "/var/tmp/${SCRIPTNAME}.lock"
+  if [ $? -ne 0 ]; then
+    logger "PE_FAILOVER: ${SCRIPTNAME} ---> Failed to remove lockfile! Exiting..."
+    exit 4
+  fi
+  exit 0
+fi
