Merging the dump/sync processes together on the master
Removed associated scripts and cron jobs

diff --git a/templates/db_dump.sh.erb b/templates/db_dump.sh.erb
--- a/templates/db_dump.sh.erb
+++ b/templates/db_dump.sh.erb
@@ -19,3 +19,17 @@ su - pe-postgres -s '/bin/bash' -c "<%= @md5sum_command %> <%= @dump_path %>/<%=
 if [ $? -ne 0 ]; then
   logger "PE_FAILOVER: ${SCRIPTNAME} ---> [FAILURE] Failed to create MD5Sum for export!"
 fi
+
+/bin/logger "PE_FAILOVER: ${SCRIPTNAME} ---> [SUCCESS] Starting sync of Puppet DB Dump directory to <%= @passive_master %>"
+
+<%= @rsync_command %> \
+  -e '/usr/bin/ssh -i <%= @rsync_user_ssh_id %>' --exclude 'archive' \
+  <%= @dump_path %>/* <%= @rsync_user %>@<%= @passive_master %>:<%= @dump_path %>/ 
+
+result="$?"
+if [[ $result -eq 0 ]]; then
+  /bin/logger "PE_FAILOVER: ${SCRIPTNAME} ---> [SUCCESS] Completed sync of Puppet DB Dump directory to <%= @passive_master %>"
+else
+  /bin/logger "PE_FAILOVER: ${SCRIPTNAME} ---> [FAILURE] Failed to sync. Exit code is: ${result}"
+fi
+
diff --git a/templates/nc_dump.sh.erb b/templates/nc_dump.sh.erb
--- a/templates/nc_dump.sh.erb
+++ b/templates/nc_dump.sh.erb
@@ -14,6 +14,16 @@ curl $NC_CURL_OPT --insecure https://$PRIMARY_MASTER:4433/classifier-api/v1/grou
 if [ $? -ne 0 ]; then
   logger "PE_FAILOVER: ${SCRIPTNAME} ---> [FAILURE] Failed to export NC data, error code: $?"
 else
-  logger "PE_FAILOVER: ${SCRIPTNAME} ---> [SUCCESS] Export Completed."
-fi
+  logger "PE_FAILOVER: ${SCRIPTNAME} ---> [SUCCESS] Export Completed. Attempting to sync data to ${SECONDARY_MASTER}"
 
+  <%= @rsync_command %> \
+    -e '/usr/bin/ssh -i <%= @rsync_user_ssh_id %>' --exclude 'archive' \
+    <%= @nc_dump_path %>/* <%= @rsync_user %>@<%= @passive_master %>:<%= @nc_dump_path %>/
+
+  result="$?"
+  if [[ $result -eq 0 ]]; then
+    logger "PE_FAILOVER: ${SCRIPTNAME} ---> [SUCCESS] Completed sync of Puppet NC Dump directory to <%= @passive_master %>"
+  else
+    logger "PE_FAILOVER: ${SCRIPTNAME} ---> [FAILURE] Failed to sync. Exit code is: ${result}"
+  fi
+fi
