Updated logging messages to make them searchable

diff --git a/templates/nc_dump.sh.erb b/templates/nc_dump.sh.erb
--- a/templates/nc_dump.sh.erb
+++ b/templates/nc_dump.sh.erb
@@ -9,11 +9,11 @@ declare -x PE_KEY=$(puppet agent --configprint hostprivkey)
 declare -x PE_CA=$(puppet agent --configprint localcacert)
 declare -x NC_CURL_OPT="-s --cacert $PE_CA --cert $PE_CERT --key $PE_KEY --insecure"
 
-logger "PE_FAILOVER: ${SCRIPTNAME} ---> Starting NC Export"
+logger "PE_FAILOVER: ${SCRIPTNAME} ---> [SUCCESS] Starting NC Export"
 curl $NC_CURL_OPT --insecure https://$PRIMARY_MASTER:4433/classifier-api/v1/groups|sed "s/$PRIMARY_MASTER/$SECONDARY_MASTER/g" > <%= @nc_dump_path %>/nc_dump.latest.json
 if [ $? -ne 0 ]; then
-  logger "PE_FAILOVER: ${SCRIPTNAME} ---> ERROR! Failed to export NC data, error code: $?"
+  logger "PE_FAILOVER: ${SCRIPTNAME} ---> [FAILURE] Failed to export NC data, error code: $?"
 else
-  logger "PE_FAILOVER: ${SCRIPTNAME} ---> Export Completed."
+  logger "PE_FAILOVER: ${SCRIPTNAME} ---> [SUCCESS] Export Completed."
 fi
 
